version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: build/nginx.docker
    restart: on-failure
    networks:
      - symfony
  php:
    build:
      context: .
      dockerfile: build/php.docker
    restart: on-failure
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:${MYSQL_PORT}/${MYSQL_DATABASE}?serverVersion=5.7
    user: ${LOCAL_USER}
    networks:
      - symfony
  mysql:
    image: mysql:8.0
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - symfony
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
    networks:
      - symfony

networks:
  symfony: