version: '3'

services:
  nginx:
    volumes:
      - ./app/:/var/www/app/
    ports:
      - ${NGINX_PORT}:80
  php:
    volumes:
      - ./app/:/var/www/app/
  mysql:
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
  phpmyadmin:
    ports:
      - ${PHPMYADMIN_PORT}:80

networks:
  symfony: